name: Audit Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run audit script
        run: python github-audit-workflow/audit/create_audit.py ${{ github.actor }} ${{ github.event.pull_request.number }}